### ISSUE TITLE
Service communication

### ISSUE THREAD

**Issue by FunnyDevs** [Xiaofei-it/Hermes#10]
Hi! Is possibile use this library for a communication Activity- Service???

**Comment by Xiaofei-it** [comment]
Yes. You can use it for communication between any components.

**Comment by FunnyDevs** [comment]
But only if the are on different processes, or even if the components are in the same process?

**Comment by Xiaofei-it** [comment]
You can use it for communication between any components in different processes, for instance, an `Activity` in Process A and a `Service` in Process B, or an `Activity` in Process A and a singleton in Process B.

You may refer to the "app" module in Hermes project or the [Demo](https://github.com/Xiaofei-it/Hermes-IPC-Demo).
