### ISSUE TITLE
Can't send or receive data larger then 100k

### ISSUE THREAD

**Issue by ghost** [Xiaofei-it/Hermes#3]
For example, I changed this code in demo UserManager class.

``` java
    @MethodId("getUser")
    @Override
    public String getUser() {
        // I tried 64k works.
        return new String(new byte[1024*100]);
    }
```

This got exception:

```
07-07 15:59:59.325 25466-25466/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
07-07 15:59:59.325 25466-25466/? E/HERMES_INVOCATION: Error occurs. Error 1: Remote Exception: Check whether the process you are communicating with is still alive.
```

I suppose this hit the limit of android IPC max data size. But 100k or 10m is not a big size for modern android device.

**Comment by Xiaofei-it** [comment]
Thank you for your feedback.
In my development, I have not passed such a large object over IPC. As you have seen, Android does not support extremely large object transmission between processes. And although 100k is not a big size, we do not transmit such a large object between processes. Instead we always put this object in a file and the other process reads the object from the file.
I have thought of an idea to solve this problem, by simply breaking the data into several parts and transmitting them one by one. But it is a little difficult to write the code.
So, do you always need to pass large objects over IPC? If so, I will write the code in the future to support large object transmission. If not, you can use other techniques, such as putting the object into the file, as mentioned above.

**Comment by ghost** [comment]
Agree with you. There is few chance to transmission large object across processes in the most of cases. But the difficult point is we don't know when a large object appeared. E.g. we give developer an api with returned type of ArrayList. The list size could be 1 or 1k. 
One of my cases needs to transmission such large object. 

Shared file is one of the solutions for this. It's not bad but not good as I think.

My current solution is to try to use streaming over IPC. 
See here: https://github.com/abeluck/android-streams-ipc
But don't know the final result about it. For example, performance and stability, etc.

I also saw some other solution about this. For example, embed a message broker(ActiveMQ) in app. A little bit heavy for me as I think

Btw, 
Do you think make Channel as pluggable component to adapt different communication protocols. IPC / Streaming IPC / JMS / Shared File are all choices to be implemented.

**Comment by Xiaofei-it** [comment]
In Linux (Android is based on Linux) there are a lot of techniques to do the IPC, one of which is called "named pipes". It is similar to the "channel" or "message queue". But there are also some other techniques, such as Socket and shared memory.
I do not quite understand your question in the last paragraph. It seems that you think channel is the basic technique which all of the IPC techniques are based on. But as mentioned above, channel is not the only one.
Android makes IPC easier by introducing Binder. And AIDL is just based on the Binder.
In Hermes, I use Binder to do the IPC, just providing an elegant way for users to make the IPC easier.

**Comment by ghost** [comment]
> I do not quite understand your question in the last paragraph. It seems that you think channel is the basic technique which all of the IPC techniques are based on. But as mentioned above, channel is not the only one.

What I mean is: If Channel is an interface IChanel then IPCChannel/StreamingIPCChannel/JMSChannel/SocketChannel/ etc. could be implementations.

**Comment by Xiaofei-it** [comment]
Of course and I think so. But actually all kinds of IPC or RPC can be abstracted and regarded as method invocation. Channel is just a way to pass the parameter to the method.
For example, if you want to upload a file to a server, you build a channel to transmit the file, and the server stores the file in some place. Now you can regard this procedure as that you invoke a method on the server, which take a file as a parameter and store the file in some place on the server. In the implementation of the method, a channel is built and the file is transmitted through the channel. But you do not need to know that. What you need to know is neither how the method is implemented, nor how the channel is built, but what method you should call.
When it comes to Hermes, Hermes provides a way to invoke a method in another process. You need not know how the data is passed to the other process.

**Comment by ghost** [comment]
I provided one of the solutions to enhance Hermes. Maybe I got misunderstanding of architecture of Hermes.

Eventually, supporting large object invocation is what I am most interesting in for now.

**Comment by Xiaofei-it** [comment]
If you finish your work, you can create a pull request.
