### ISSUE TITLE
Activity 作为参数传递

### ISSUE THREAD

**Issue by guobao90** [Xiaofei-it/Hermes#6]
我看了代码，如果Activity作为参数传递，接收到的是对方进程的Application context . 正常跳转是没问题，但是如果是需要返回值的startActivityForResult。就需要取得Activity的实例进行跳转。context 是不包含此方法的。我要怎么去获取传递过来的Activity 的实例？

**Comment by Xiaofei-it** [comment]
这种需求很罕见啊，当初考虑过这个，就是因为罕见，所以没管它。
