### ISSUE TITLE
不理解

### ISSUE THREAD

**Issue by Labradors** [Xiaofei-it/Hermes#8]
看了半天，还是不理解。

**Comment by Xiaofei-it** [comment]
哪里不理解啊？

readme里有一个demo可以参考。还有一个HermesEventBus库就是基于这个库的，你也可以参考。

另外，Hermes库的app文件夹下也是一个测试的demo。

**Comment by Labradors** [comment]
项目中希望拿到长连接的引用，因为不能序列化。所以看到你这个库。我看到有很多个service，但具体是干嘛的不太清楚，还有，我看到你的demo中写到别的进程调用主进程的单例，但是，如果主进程调用别的进程的单例呢？具体是在哪里初始化？在哪里进行连接？

**Comment by Xiaofei-it** [comment]
Hermes库的进程不分主从。你可以在主进程里获取子进程内的单例。

具体做法：在manifest里声明一个HermesService，process属性设为子进程。然后子进程init，主进程connect子进程，使用`connect(Context, Class<? extends HermesService>)`方法connect子进程，第二个参数是你之前声明的HermesService。然后就可以使用了。

**Comment by Labradors** [comment]
@Xiaofei-it 比如，我声明一个RemoteService，继承自HermesService，按照上面你说的就行了，对吗？

**Comment by Xiaofei-it** [comment]
你看HermesService类，里面有已经写好的内部类给你用，你直接用就可以了，不用再继承。

**Comment by Xiaofei-it** [comment]
有一个[高级教程](https://github.com/Xiaofei-it/Hermes/blob/master/AdvancedTutorial.md)
